CREATE DATABASE users;
CREATE USER 'user'@'${SERVER_IP}' IDENTIFIED BY '${USER_PASS}';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'user'@'${SERVER_IP}' WITH GRANT OPTION;
FLUSH PRIVILEGES;
exit
